# Generated by Django 4.0.4 on 2022-05-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='postal_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='town',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='zip_code',
            field=models.CharField(max_length=200),
        ),
    ]
