# Generated by Django 4.1.1 on 2022-12-27 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_member_country_alter_member_postal_code_and_more'),
        ('savings', '0003_alter_saving_member_alter_transaction_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='savings', to='users.member'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.member'),
        ),
    ]
